version: "2.3"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    restart: "always"
    volumes:
      - ./:/usr/src/app
    depends_on: 
      - db
    networks:
      - app_network
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - app_network
networks:
  app_network:
    driver: bridge

